### ISSUE TITLE
Participate in Google Summer of Code

### ISSUE THREAD

**Issue by XVilka** [SymbiFlow/ideas#22]
Might be beneficial for the project, attract more attention and contributors.

The application starts in three weeks:
- January 15 20:00 UTC | Mentoring organizations can begin submitting applications to Google
- February 6 20:00 UTC | Mentoring organization application deadline

See https://developers.google.com/open-source/gsoc/timeline

**Comment by programmerjake** [comment]
reminder that the deadline is quite soon

**Comment by mithro** [comment]
I have started putting together an application for GSoC. The best thing people can do to help is to improve (and add) ideas in this issue tracker.

See some tips at https://github.com/sympy/sympy/wiki/GSoC-2018-Ideas and https://google.github.io/gsocguides/mentor/defining-a-project-ideas-list

**Comment by mithro** [comment]
@kgugala @mgielda @pgielda - You are probably interested in this.

**Comment by XVilka** [comment]
Deadline is tomorrow by the way.

**Comment by mithro** [comment]
Just FYI - Deadline for applications is actually February 7, 2019 at 07:00 (Australian Eastern Daylight Time).

I believe we have put in an application. If we are not successful in our application we will look at participating via an organisation like [TimVideos](https://code.timvideos.us/home/) or [FOSSi Foundation](https://fossi-foundation.org/) (assuming they are accepted).

**Comment by mithro** [comment]
(Wednesday, February 6th at 20:00 UTC for those not in my timezone :-)

**Comment by XVilka** [comment]
Congratulations! You got selected 🥇  Closing then as solved.

https://summerofcode.withgoogle.com/organizations/4517422304854016/

**Comment by XVilka** [comment]
To everyone involved - just a reminder that GSoC 2020 organization applications will be open on January 15 until February 6 - https://summerofcode.withgoogle.com/how-it-works/#timeline
