### ISSUE TITLE
Join the forces with The OpenROAD project

### ISSUE THREAD

**Issue by XVilka** [SymbiFlow/ideas#24]
https://theopenroadproject.org/

https://github.com/The-OpenROAD-Project

https://theopenroadproject.org/wp-content/uploads/2018/12/OpenROAD_Flow_and_Notes_Nov2018-v1p0-1.pdf

**Comment by mithro** [comment]
The open road project is mainly targeting ASICs. They are also an academic drive project with funding from DARPA which makes it hard for external parties to contribute.

 There may be some areas we can collaborate around Synthesis but it seems unlikely to be anything else at least in the short term.
